-- Float → Decimal migration for all money fields across all models
-- Converts ~60+ money/price columns from DOUBLE PRECISION to DECIMAL(18,4)
-- Non-money fields (quantity, coordinates, exchange rate) remain Float

-- AlterTable
ALTER TABLE "AppSettings" ALTER COLUMN "vatRate" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "usdToLbpRate" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "deliveryFee" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "DailyClose" ALTER COLUMN "grossSales" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "refunds" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "netSales" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "costOfGoods" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "returnedCost" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "grossMargin" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "expenses" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "supplierPayments" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "netProfit" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cashIn" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cashOut" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "DebtPayment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "DebtSale" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "discountTotal" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "tax" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "DeliveryOrder" ALTER COLUMN "itemsTotal" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "deliveryFee" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "paidAmount" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "changeRequired" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "DeliveryOrderItem" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "InventoryBatch" ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "PurchaseOrder" ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "paidTotal" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "PurchaseOrderItem" ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "RefundItem" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "discountTotal" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "tax" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "profit" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "SaleItem" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "SaleRefund" ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "SaleTender" ALTER COLUMN "paidUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "paidLbp" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "paidTotalUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "paidTotalLbp" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "changeUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "changeLbp" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "Shift" ALTER COLUMN "openingFloatUsd" DROP NOT NULL,
ALTER COLUMN "openingFloatUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cashSalesUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cashRefundsUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "cashExpensesUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "supplierPaymentsUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "expectedCashUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "closingCashUsd" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "differenceUsd" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "StockAdjustment" ALTER COLUMN "valueImpact" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "StockCountLine" ALTER COLUMN "valueImpact" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "StockCountSession" ALTER COLUMN "totalVariance" SET DATA TYPE DECIMAL(18,4),
ALTER COLUMN "totalValueImpact" SET DATA TYPE DECIMAL(18,4);

-- AlterTable
ALTER TABLE "SupplierPayment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(18,4);
